# Server configuration
server:
  port: 8081
  servlet:
    context-path: /identity

google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}
  redirect-uri: http://localhost:3000/authenticate


# Application properties
spring:
  application:
    name: thinh


  # Scheduling (optional, enabled by default if @EnableScheduling is present)
  # spring.task.scheduling.pool.size — the number of threads available to run scheduled tasks concurrently.
  # Only one thread will run all scheduled tasks.-->size: 1
  # Tasks will run sequentially (one at a time).
  #If you have multiple scheduled tasks and one task takes a long time, the others will wait.
  # size: 5--> Use up to 5 threads, run scheduled tasks concurrently
  task:
    scheduling:
      pool:
        size: 1

  # Datasource configuration
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/identity_service}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# JWT
jwt:
  valid-expiration: 3600        # 60 minutes = 60 * 60 = 3600
  refreshable-duration: 86400  # 1 day = 24 * 60 * 60 = 86400
  secretKey: YTJqdRD3fVs4s11groDPXypfQj3skk0x+pU4FV7M2sA=
