# Server configuration
server:
  port: 8081
  servlet:
    context-path: /identity

# Application properties
spring:
  application:
    name: thinh


  # Scheduling (optional, enabled by default if @EnableScheduling is present)
  # spring.task.scheduling.pool.size — the number of threads available to run scheduled tasks concurrently.
  # Only one thread will run all scheduled tasks.-->size: 1
  # Tasks will run sequentially (one at a time).
  #If you have multiple scheduled tasks and one task takes a long time, the others will wait.
  # size: 5--> Use up to 5 threads, run scheduled tasks concurrently
  task:
    scheduling:
      pool:
        size: 1

  # Datasource configuration
  datasource:
    url: jdbc:mysql://localhost:3306/identity_service
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# JWT
jwt:
  valid-expiration: 20
  refreshable-duration: 120
  secretKey: YTJqdRD3fVs4s11groDPXypfQj3skk0x+pU4FV7M2sA=
