# Server configuration
server:
  port: 8081
  servlet:
    context-path: /identity

# Application properties
spring:
  application:
    name: thinh

  # Datasource configuration
  datasource:
    url: jdbc:mysql://localhost:3306/identity_service
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# JWT
jwt:
  expiration: 3600 # seconds
  refreshable-duration: 3600
  secretKey: YTJqdRD3fVs4s11groDPXypfQj3skk0x+pU4FV7M2sA=
